// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'abilities_items': string;
  'buttons': string;
  'card': string;
  'close': string;
  'divider': string;
  'health': string;
  'image': string;
  'info': string;
  'label': string;
  'progress': string;
  'root': string;
  'stats': string;
  'stats_block': string;
  'stats_number': string;
  'stats_text': string;
  'text': string;
  'title': string;
  'title_id': string;
  'title_primary': string;
  'title_right': string;
  'title_row': string;
  'title_secondary': string;
  'types': string;
  'whiteBlock': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
